spring:
    freemarker:
        templateLoaderPath: classpath:/templates/
        #不检查模板路径
        checkTemplateLocation: false
        charset: UTF-8

server:
  port: 8000

logging:
    level:
        com.learn.*: DEBUG

